name: "Flathub merge action"
description: "Flathub merge action to merge submission pull requests"
author: "Flathub contributors"
inputs:
  token:
    description: 'The token that the action will use.'
    default: ${{ github.token }}
    required: true
runs:
  using: 'docker'
  image: "docker://ghcr.io/flathub-infra/merge:latest@sha256:26713e2ca5650c503eeef6aed2d1db2d74c3ce504adb2eff2b2c86bd0eee6b76"
