name: "Flathub merge action"
description: "Flathub merge action to merge submission pull requests"
author: "Flathub contributors"
inputs:
  token:
    description: 'The token that the action will use.'
    default: ${{ github.token }}
    required: true
runs:
  using: 'docker'
  image: "docker://ghcr.io/flathub-infra/merge:latest@sha256:e4caf0309f09ae78b5d08dc6d685a08d2099c8c83959ea60f743c1b927364b9d"
